import Logger from "../utils/logger.ts";
import * as config from "../servers.json" with { type: "json" };

const SERVER_DIR = "./server";
const DEFAULT_MC_VERSION = "1.21.4";

interface VersionManifest {
  latest: { release: string; snapshot: string };
  versions: Array<{ id: string; type: string; url: string }>;
}

interface VersionDetails {
  downloads: {
    server: { url: string; sha1: string; size: number };
  };
}

async function getServerJarUrl(version: string): Promise<string> {
  Logger.info(`Fetching Minecraft version manifest...`);

  const manifestResponse = await fetch(
    "https://piston-meta.mojang.com/mc/game/version_manifest_v2.json",
  );
  const manifest: VersionManifest = await manifestResponse.json();

  const versionInfo = manifest.versions.find((v) => v.id === version);
  if (!versionInfo) {
    throw new Error(`Version ${version} not found`);
  }

  Logger.info(`Found version ${version}, fetching download URL...`);
  const versionResponse = await fetch(versionInfo.url);
  const versionDetails: VersionDetails = await versionResponse.json();

  return versionDetails.downloads.server.url;
}

async function downloadServerJar(url: string, destPath: string): Promise<void> {
  Logger.info(`Downloading server jar from ${url}...`);

  const response = await fetch(url);
  if (!response.ok) {
    throw new Error(`Failed to download: ${response.statusText}`);
  }

  const data = await response.arrayBuffer();
  await Deno.writeFile(destPath, new Uint8Array(data));

  Logger.info(`Server jar downloaded to ${destPath}`);
}

function createEula(): string {
  return `# By changing the setting below to TRUE you are indicating your agreement to our EULA (https://aka.ms/MinecraftEULA).
eula=true
`;
}

function createServerProperties(): string {
  const serverConfig = config.default.server || {};
  return `# Minecraft server properties
# Generated by tao

# Server settings
server-port=${serverConfig.port || 25565}
gamemode=${serverConfig.gamemode || "survival"}
difficulty=${serverConfig.difficulty || "normal"}
max-players=${serverConfig.maxPlayers || 20}
motd=${serverConfig.motd || "A Minecraft Server managed by tao"}
online-mode=${serverConfig.onlineMode !== false}
white-list=${serverConfig.whitelist || false}
spawn-protection=16
view-distance=10
simulation-distance=10
enable-command-block=false
op-permission-level=4
pvp=true
`;
}

function createStartScript(jarName: string, memory: string): string {
  return `#!/bin/bash
java -Xmx${memory} -Xms${memory} -jar ${jarName} nogui
`;
}

export async function setup(): Promise<void> {
  Logger.info("Starting Minecraft server setup...");

  const serverConfig = config.default.server || {};
  const version = serverConfig.version || DEFAULT_MC_VERSION;
  const memory = serverConfig.memory || "2G";

  // Create server directory
  try {
    await Deno.mkdir(SERVER_DIR, { recursive: true });
    Logger.info(`Created server directory: ${SERVER_DIR}`);
  } catch (error) {
    if (!(error instanceof Deno.errors.AlreadyExists)) {
      throw error;
    }
    Logger.info(`Server directory already exists: ${SERVER_DIR}`);
  }

  // Download server jar
  const jarName = `server-${version}.jar`;
  const jarPath = `${SERVER_DIR}/${jarName}`;

  try {
    await Deno.stat(jarPath);
    Logger.info(`Server jar already exists: ${jarPath}`);
  } catch {
    const jarUrl = await getServerJarUrl(version);
    await downloadServerJar(jarUrl, jarPath);
  }

  // Create eula.txt
  const eulaPath = `${SERVER_DIR}/eula.txt`;
  await Deno.writeTextFile(eulaPath, createEula());
  Logger.info(`Created ${eulaPath}`);

  // Create server.properties
  const propsPath = `${SERVER_DIR}/server.properties`;
  await Deno.writeTextFile(propsPath, createServerProperties());
  Logger.info(`Created ${propsPath}`);

  // Create start script
  const startScriptPath = `${SERVER_DIR}/start.sh`;
  await Deno.writeTextFile(startScriptPath, createStartScript(jarName, memory));
  await Deno.chmod(startScriptPath, 0o755);
  Logger.info(`Created ${startScriptPath}`);

  Logger.info("Setup complete! Run 'tao start' to start the server.");
}
